measurements:
  - type: ping
    target: discord.com
    description: "Ping measurement to Discord DNS"
    interval: 300  
    duration_hours: 1
    af: 4  # IPv4
    probes:
      area: "South-Central"  
      count: 10


  - type: traceroute
    target: discord.com
    description: "Traceroute to Discord"
    protocol: "ICMP"
    interval: 900  
    duration_hours: 2
    af: 4
    probes:
      area: "South-East"
      count: 10
    

  # - type: ping
  #   target: facebook.com
  #   description: "Ping measurement to Facebook"
  #   interval: 240
  #   duration_hours: 1
  #   af: 4
  #   probes:
  #     area: "North America"
  #     count: 6
