measurements:
  - type: ping
    target: github.com
    description: "Ping measurement to Discord DNS from Japan"
    interval: 300  
    duration_hours: 1
    af: 4  # IPv4
    probes:
      country: "JP"  
      count: 10


  - type: traceroute
    target: discord.com
    description: "Traceroute to Discord from India"
    protocol: "ICMP"
    interval: 900  
    duration_hours: 2
    af: 4
    probes:
      country: "IN" 
      count: 10
    

  # Example using area (original functionality still works)
  # - type: ping
  #   target: facebook.com
  #   description: "Ping measurement to Facebook"
  #   interval: 240
  #   duration_hours: 1
  #   af: 4
  #   probes:
  #     area: "North America"
  #     count: 6
