# This is a configuration file for Sintra measurement client
# It defines various network measurements to be performed
# Each measurement has a type, target, description, interval, duration, address family (af
# and probes
measurements:
  - type: ping # ping or traceroute
    target: github.com # target domain or IP address
    description: "Ping measurement to github DNS from Japan"  # Description of the measurement
    interval: 300  # Interval in seconds
    duration_hours: 1 # Duration in hours
    af: 4  # Address family (4 for IPv4, 6 for IPv6)
    probes:
      country: "JP"  # Country code for the probe location
      count: 10 # Number of probes to use


  - type: traceroute # ping or traceroute
    target: discord.com # target domain or IP address
    description: "Traceroute to Discord from India" # Description of the measurement
    protocol: "ICMP" # Protocol to use (ICMP, TCP, UDP)
    interval: 900  # Interval in seconds
    duration_hours: 2 # Duration in hours
    af: 4 # Address family (4 for IPv4, 6 for IPv6)
    probes:
      country: "IN" # Country code for the probe location
      count: 10 # Number of probes to use
    

  # Example using area (original functionality still works)
  # - type: ping
  #   target: facebook.com
  #   description: "Ping measurement to Facebook"
  #   interval: 240
  #   duration_hours: 1
  #   af: 4
  #   probes:
  #     area: "North America"
  #     count: 6
